name: CI

on: ['push', 'pull_request']

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
              "**.js"
              

  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        experimental: [false]
        runtime: [node, deno, bun]
        pm: [npm, pnpm, yarn]
    name: 👷 CI ${{ matrix.runtime }} on ${{ matrix.os }} with ${{ matrix.pm }}

    timeout-minutes: 60

    steps:
      - name: 🚚 Checkout repository
        uses: actions/checkout@v4

      - name: Setup Test Environment
        uses: siguici/setup-js@v1
        with:
          runtime: ${{ matrix.runtime }}
          pm: ${{ matrix.pm }}

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projetozipado.zip

      - name: Baixando o artefato
        run: ls -R
    

    